FROM mysql:5.7

COPY docker/db/my.cnf /etc/mysql/conf.d/my.cnf
COPY docker/db/mysql-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/mysql-entrypoint.sh
ENTRYPOINT ["mysql-entrypoint.sh"]

EXPOSE 3306
